config/routes.rb
Rails.application.routes.draw do

  post ':doggo_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':doggo_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'howls#browse', as: :browse_howls

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  resources :howls do
    resources :barkbacks
    member do
      get 'love'
      get 'unlove'
    end
    resources :scents, only: [:create]
  end

  resources :barkbacks do
    member do
      get 'love'
      get 'unlove'
    end
  end

  root 'howls#index'

  get ':doggo_name', to: 'profiles#show', as: :profile
  get ':doggo_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':doggo_name/edit', to: 'profiles#update', as: :update_profile

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :my_profile, only: [:edit, :update]
  before_action :set_user

  def show
    @howls = @user.howls.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your Doggo profile has been updated!'
      redirect_to profile_path(@user.doggo_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

    def profile_params
      params.require(:user).permit(:avatar, :bio, :doggo_name)
    end

    def my_profile
      @user = User.find_by(doggo_name: params[:doggo_name])
      unless current_user == @user
        flash[:alert] = "Paws off! Your are not the doggo we're looking for!"
        redirect_to root_path
      end
    end

    def set_user
      @user = User.find_by(doggo_name: params[:doggo_name])
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium), id: 'image-preview', class: "img-responsive img-circle profile-image" if user.avatar.exists?
    image_tag 'default-profile.jpg', id: 'image_preview', class: "img-responsive img-circle profile-image"
  end
end

app/views/profiles/edit.html.erb
<div class="howls-wrapper">
  <div class="howl">
    <div class="howl-body">
      <div class="image-wrap">
        <%= form_for @user, url: { action: "update" }, html: { multiport: true } do |f| %>
          <div class="row">
            <div class="col-mid-12">
              <div class="form-group text-center">
                <h4>Change your Doggo's name:</h4>
                <%= f.text_field :doggo_name, required: true, label: false, placeholder: @user.doggo_name, input_html: { class: 'input-lg' } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-mid-12">
              <div class="form-group text-center">
                <h4>Change your Doggo's selfie:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, label: false, input_html: { onChange: 'loadFile(event)' } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-mid-12">
              <div class="form-group text-center">
                <h4>Bark a bit about yourself!</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="howls-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="doggo-name-and-follow">
        <h3 class="profile-doggo-name"><%= @user.doggo_name %></h3>
        <span>
          <% if @user == current_user %>
            <%= link_to "Edit Profile", edit_profile_path(@user.doggo_name), class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id) %>
              <%= link_to "Tracking", unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% else %>
              <%= link_to "Track", follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
            <% end %>
          <% end %>
        </span>

        <p class="profile-bio"><%= @user.bio %></p>
        <div class="user-statistics">
          <p><%= pluralize @user.howls.count, 'howl' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<% @howls.each do |howl| %>
  <%= render 'howls/howl', howl: howl %>
<% end %>