config/routes.rb
Rails.application.routes.draw do

  post ':doggo_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':doggo_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'howls#browse', as: :browse_howls

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  resources :howls do
    resources :barkbacks
    member do
      get 'love'
      get 'unlove'
    end
    resources :scents, only: [:create]
  end

  resources :barkbacks do
    member do
      get 'love'
      get 'unlove'
    end
  end

  root 'howls#index'

  get ':doggo_name', to: 'profiles#show', as: :profile
  get ':doggo_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':doggo_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/howl.rb
class Howl < ActiveRecord::Base
  acts_as_votable

  validates :image, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }
  validates :user_id, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  has_many :scents, dependent: :destroy
  has_many :barkbacks, dependent: :destroy

  scope :of_followed_users, -> (following_users) { where user_id: following_users }

  def scents_attributes=(scents_attributes)
    scents_attributes.values.each do |attr|
      self.scents.build(attr)
    end
  end
end

app/controllers/howls_controller.rb
class HowlsController < ApplicationController
  before_action :set_howl, only: [:show, :edit, :update, :destroy, :love, :unlove]
  before_action :owned_howl, only: [:edit, :update, :destroy]

  def index
    @howls = Howl.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @howls }
      format.js
    end
  end

  def browse
    @howls = Howl.all.order('created_at DESC').page params[:page]
    respond_to do |format|
      format.html { render :browse }
      format.json { render json: @howls }
      format.js
    end
  end

  def new
    @howl = current_user.howls.build
  end

  def create
    @howl = current_user.howls.build(howl_params)

    if @howl.save
      flash[:success] = "You have Howled loud and clear for all to hear!"
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @howl }
      end
    else
      flash.now[:alert] = "Your boofer seems to be broken. Try again!"
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @howl }
      format.js
    end
  end

  def edit
  end

  def update
    if @howl.update(howl_params)
      flash[:success] = "HOOOOOWWWWWLL!!!!!"
      render :show
    else
      flash.now[:alert] = "Your re-boofer isn't boofing. Boof again."
      render :edit
    end
  end

  def destroy
    @howl.destroy
    flash[:alert] = "That boofer has been muzzled for good."
    redirect_to root_path
  end

  def love #liked_by is an 'acts_as_votable' method
    if @howl.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlove
    if @howl.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private
    def howl_params
      params.require(:howl).permit(:image, :caption, scents_attributes: [:stench, :howl_id])
    end

    def set_howl
      @howl = Howl.find(params[:id])
    end

    def owned_howl
      unless current_user == @howl.user
        flash[:alert] = "Paws off! That's not your howl!"
        redirect_to root_path
      end
    end

end

app/helpers/howls_helper.rb
module HowlsHelper
  def form_image_select(howl)
    return image_tag howl.image.url(:medium), id: 'image-preview', class: 'img-responsive' if howl.image.exists?
    image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end

  def display_loves(howl)
    votes = howl.votes_for.up
    return list_lovers(votes) if votes.size <= 8
    count_lovers(votes)
  end

  def loved_howl(howl)
    return 'glyphicon-heart' if current_user.voted_for? howl
    'glyphicon-heart-empty'
  end

  private

    def list_lovers(votes)
      doggo_names = []
      unless votes.blank?
        votes.voters.each do |voter|
          doggo_names.push(link_to voter.doggo_name, profile_path(voter.doggo_name), class: 'doggo-name')
        end
        doggo_names.to_sentence.html_safe + love_plural(votes)
      end
    end

    def count_lovers(votes)
      vote_count = votes.size
      vote_count.to_s + ' loves'
    end

    def love_plural(votes)
      return 'love this' if votes.count > 1
      'loves this'
    end
end

app/views/howls/_form.html.erb
<div class="howls-wrapper">
  <div class="howl">
    <div class="howl-body">
      <div class="image-wrap">
        <%= form_image_select(@howl) %>
        <%= simple_form_for @howl, html: { multiport: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Woof?' %>
            </div>
            <div class="form-group text-center">
              <%= f.simple_fields_for :scents, @howl.scents.build do |f| %>
                <%= f.input :stench, collection: Scent.stenches.keys.map { |s| [s.humanize, s] }, class: 'howl-scents-select' %>
                <%= f.hidden_field :howl_id, :value => @howl.id %>
              <% end %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/howls/_howl.html.erb
<div class="howls-wrapper">
  <div class="howl">
    <div class="howl-head">
      <div class="doggo-name">
        <%= link_to howl.user.doggo_name, profile_path(howl.user.doggo_name) %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words howl.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag howl.image.url(:medium), class: 'img-responsive'), howl_path(howl) %>
    </div>
    <div class="howl-bottom">
      <%= render 'howls/loves', howl: howl %>
      <p class="caption"><span class="doggo-name"><%= link_to howl.user.doggo_name, profile_path(howl.user.doggo_name) %></span> <%= howl.caption %></p>
      <p class="human_name">My human: <%= howl.user.human_name %></p>
      <div class="barkbacks" id="barkbacks_<%=howl.id%>">
        <p class="caption">
          <button class="load_barkbacks" id="load_barkbacks" data-howl-id="<%= howl.id %>">"Load Barkbacks"</button>
        </p>
      </div>
      <div class="barkback-love-form row">
        <div class="love-button col-sm-1">
          <%= link_to '', howl.voted_on_by?(current_user) ? unlove_howl_path(howl.id) : love_howl_path(howl.id), remote: true, id: "love_#{howl.id}", class: "love glyphicon #{loved_howl howl}" %>
        </div>
        <div class="barkback-form col-sm-11">
          <%= form_for([howl, howl.barkbacks.build], data: { howl_id:  howl.id }) do |f| %>
            <%= f.text_field :content, placeholder: 'Bark back at them..!', class: "barkback_content", id: "barkback_content_#{howl.id}" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="overlap overlap-wrapper text-center">
      <div class="text">
      <%= form_for([howl, howl.scents.build], remote: true) do |f| %>
        <%= f.label :scent, "Sniff..sniff.." %>
        <%= f.select :stench, Scent.stenches.keys.map { |s| [s.humanize, s] }, class: '' %>
        <%= f.hidden_field :howl_id, :value => howl.id %>
        <%= f.submit "SNIFF", class: 'btn btn-sm btn-primary' %>
      <% end %><br>
      <span>Average Sniff Test Rating:<br> <%= sniff_test(howl).humanize %></span>
      </div>
    </div>
  </div>
</div>

app/views/howls/_howl_dashboard.html.erb
<% if @howls.empty? %>
  <p class="text-center">You aren't tracking any fellow Doggos!  Check out the "Browse" section and start tracking!</p>
<% end %>

<div id="howls">
  <%= render 'howls' %>
</div>

<% if @howls.next_page %>
  <div class="text-center" id="paginator">
    <%= link_to_next_page @howls, 'MOAR HOOOOWLS!', remote: true, id: 'moar' %>
  </div>
<% end %>

app/views/howls/_howl_dashboard.js.erb
$('#howls').append("<%= escape_javascript(render 'howls')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@howls, 'MOAR HOOOOWLS!', remote: true, id: 'moar'))%>");
if (!$('moar').length) { $('#paginator').remove(); }  

app/views/howls/_howls.html.erb
<%= render @howls %>

app/views/howls/browse.html.erb
<%= render 'howl_dashboard', howls: @howls %>

app/views/howls/browse.js.erb
$('#howls').append("<%= escape_javascript(render 'howls')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@howls, 'MOAR HOOOOWLS!', remote: true, id: 'moar'))%>");
if (!$('#moar').length) { $('#paginator').remove(); }

app/views/howls/edit.html.erb
<%= render 'form' %>

<div class="text-center edit-links">
  <%= link_to "Cancel", howl_path(@howl) %>
  |
  <%= link_to "Delete Howl", howl_path(@howl), method: :delete, data: { confirm: "Are you sure you want to delete this howl?"} %>
</div>

app/views/howls/index.html.erb
<div id="howls">
    <%= render 'howls' %>
</div>

<div class="text-center" id="paginator">
  <%= link_to_next_page @howls, 'MOAR HOOOOWLS!', remote:true, id: 'moar' %>
</div>

app/views/howls/index.js.erb
$('#howls').append("<%= escape_javascript(render 'howls')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@howls, 'MOAR HOOOOWLS!', remote: true, id: 'moar'))%>");
if (!$('#moar').length) { $('#paginator').remove(); }

app/views/howls/love.js.erb
$("#love_<%= @howl.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart').prop('href', '<%= unlove_howl_path(@howl.id) %>');
$("#loves_<%= @howl.id %>").html("<%= j (render partial: 'howls/loves', locals: { howl: @howl} ) %>");

app/views/howls/new.html.erb
<%= render 'form' %>

app/views/howls/show.html.erb
<div class="">
  <%= render 'howl', howl: @howl %>
  <div class="text-center edit-links">
    <%= link_to "Home", howls_path, class: "" %>
    <% if @howl.user == current_user %>
      |
      <%= link_to "Edit Howl", edit_howl_path(@howl) %>
    <% end %>
  </div>
</div>

app/views/howls/unlove.js.erb
$("#love_<%= @howl.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty').prop('href', '<%= love_howl_path(@howl.id) %>')
$("#loves_<%= @howl.id %>").html("<%= j (render partial: 'howls/loves', locals: { howl: @howl } ) %>")