config/routes.rb
Rails.application.routes.draw do

  post ':doggo_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':doggo_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'howls#browse', as: :browse_howls

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  resources :howls do
    resources :barkbacks
    member do
      get 'love'
      get 'unlove'
    end
    resources :scents, only: [:create]
  end

  resources :barkbacks do
    member do
      get 'love'
      get 'unlove'
    end
  end

  root 'howls#index'

  get ':doggo_name', to: 'profiles#show', as: :profile
  get ':doggo_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':doggo_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/barkback.rb
class Barkback < ApplicationRecord
  belongs_to :user
  belongs_to :howl

  acts_as_votable
end

app/controllers/barkbacks_controller.rb
class BarkbacksController < ApplicationController
  before_action :set_howl, except: [:love, :unlove]
  before_action :set_barkback, only: [:love, :unlove]

  def index
    @barkbacks = @howl.barkbacks.order("created_at ASC")

    respond_to do |format|
      format.json { render :json => @barkbacks }
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @barkback = @howl.barkbacks.build(barkback_params)
    @barkback.user_id = current_user.id

    if @barkback.save
      respond_to do |format|
        format.json { render :json => @barkback }
        format.html { redirect_to root_path }
      end
    else
      flash[:alert] = "That's not much of a bark. Unmuzzle yourself and try again!"
      render root_path
    end
  end

  def new
    @barkback = @howl.barkbacks.new
  end

  def show
    @barkback = @howl.barkbacks.find(params[:id])
  end

  def destroy
    @barkback = @howl.barkbacks.find(params[:id])

    if @barkback.user_id == current_user.id
      @barkback.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def love #liked_by is an 'acts_as_votable' method
    if @barkback.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlove
    if @barkback.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private
    def barkback_params
      params.require(:barkback).permit(:content, scents_attributes: [:stench, :howl_id])
    end

    def set_howl
      @howl = Howl.find(params[:howl_id])
    end

    def set_barkback
      @barkback = Barkback.find(params[:id])
    end

end

app/helpers/barkbacks_helper.rb
module BarkbacksHelper
  def loved_barkback(barkback)
    return 'glyphicon-heart' if current_user.voted_for? barkback
    'glyphicon-heart-empty'
  end
end

app/views/barkbacks/_barkback.html.erb
<div class="" id="barkback">
  <p class="barkback-content"><span class="doggo-name"><%= link_to barkback.user.doggo_name, profile_path(barkback.user.doggo_name) %></span> <%= barkback.content %></p>
  <% if barkback.user == current_user %>
    <%= link_to howl_barkback_path(howl, barkback), method: :delete, data: { confirm: "Muzzle this barkback? Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-barkback-icon"></span>
    <% end %>
  <% else %>
    <%= link_to '', barkback.voted_on_by?(current_user) ? unlove_barkback_path(barkback.id) : love_barkback_path(barkback.id), remote: true, id: "love_#{barkback.id}", class: "love love-barkback-icon glyphicon #{loved_barkback barkback}" %>
  <% end %>
</div>

app/views/barkbacks/create.js.erb
//$('#barkbacks_<%#= @howl.id %>').append("<%#=j render 'barkbacks/barkback', howl: @howl, barkback: @barkback %>");
//$('#barkback_content_<%#= @howl.id %>').val('')

app/views/barkbacks/destroy.js.erb
$('#barkbacks_<%= @howl.id %>').html("<%= j render @howl.barkbacks, howl: @howl, barkback: @barkback %>");
Append.barkback_count -= 1

app/views/barkbacks/index.html.erb
<%= render @barkbacks, howl: @howl %>

app/views/barkbacks/new.html.erb
<div class="barkback-form col-sm-11">
  <%= simple_form_for([@howl, @howl.barkbacks.build]) do |f| %>
    <%= f.input :content, placeholder: 'Bark back at them..!', class: "barkback_content", id: "barkback_content_#{@howl.id}" %>
  <% end %>
</div>

app/views/barkbacks/show.html.erb
<div class="" id="barkback">
  <p class="barkback-content"><span class="doggo-name"><%= link_to @barkback.user.doggo_name, profile_path(@barkback.user.doggo_name) %></span> <%= @barkback.content %></p>
  <% if @barkback.user == current_user %>
    <%= link_to howl_barkback_path(@howl, @barkback), method: :delete, data: { confirm: "Muzzle this barkback? Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-barkback-icon"></span>
    <% end %>
  <% else %>
    <%= link_to '', @barkback.voted_on_by?(current_user) ? unlove_barkback_path(@barkback.id) : love_barkback_path(@barkback.id), remote: true, id: "love_#{@barkback.id}", class: "love love-barkback-icon glyphicon #{loved_barkback barkback}" %>
  <% end %>
</div>