config/routes.rb
Rails.application.routes.draw do

  post ':doggo_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':doggo_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'howls#browse', as: :browse_howls

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  resources :howls do
    resources :barkbacks
    member do
      get 'love'
      get 'unlove'
    end
    resources :scents, only: [:create]
  end

  resources :barkbacks do
    member do
      get 'love'
      get 'unlove'
    end
  end

  root 'howls#index'

  get ':doggo_name', to: 'profiles#show', as: :profile
  get ':doggo_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':doggo_name/edit', to: 'profiles#update', as: :update_profile

end

app/views/layouts/_flash_messages.html.erb
<div class="flash">

    <% flash.each do |type, message| %>
      <div class="alert alert-fixed <%= alert_for(type) %> alert-dismissible text-center fade in">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("doggo_brand.jpg", height: '52'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render 'layouts/sign_in' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sign_in.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <li>
      <%= link_to "Browse", browse_howls_path %>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to new_howl_path, :class => "" do %>
        <i class="glyphicon glyphicon-plus"></i> Howl
      <% end %>
    </li>
    <li>
      <%= link_to profile_path(current_user.doggo_name) do %>
        <i class="glyphicon glyphicon-user"></i> My Profile
      <% end %>
    <li>
      <%= link_to destroy_user_session_path, :method => "delete" do %>
        <i class="glyphicon glyphicon-log-out"></i> Logout
      <% end %>
    </li>
<% else %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to new_user_session_path do %>
        <i class="glyphicon glyphicon-log-in"></i> Login
      <% end %>
    </li>
    <li>
      <%= link_to new_user_registration_path do %>
        <i class="glyphicon glyphicon-user"></i> Register
      <% end %>
    </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doggo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <%= render partial: "layouts/flash_messages", flash: flash %>

  <%= yield %>

</body>
</html>